### PR TITLE
Release 0.6.5: Broken domains fix & sync coins

### PR DESCRIPTION
**Pull request by smk762**

### CODE REVIEW

**Review by CharlVS — CHANGES_REQUESTED** [review]
@smk762 Is the updated config associated with a commit from the coins repo, or are these manual hot-fix changes?
If there is a commit, please update the commit hash in `coins_ci.json` and add the associated `coins.json` file if there are changes.

**Comment by CharlVS** [comment]
Certificate errors:
image

**Comment by smk762** [comment]
Thanks, I suspected some were missed. List of urls to services in this PR for tracking:

https://komodo.earth:3334/api/v1/moonriver_tx_history :heavy_check_mark: 
https://prices.komodo.earth:1313/api/v2/tickers?expire_at=600 :heavy_check_mark: 
https://komodo.earth/messages :heavy_check_mark: 
https://komodo.earth/adexversion :heavy_check_mark: 
https://faucet.komodo.earth/  :heavy_check_mark: 

https://komodo.earth:3333/api/v1/ohlc :cactus: 
http://komodo.earth/ :cactus: (not in this PR, but needs to be fixed)

**Comment by naezith** [comment]
These work fine for me without any certificate issues.
https://komodo.earth:3333/api/v1/ohlc/tickers_list
https://komodo.earth:3333/api/v1/ohlc/btc-usdc

**Comment by CharlVS** [comment]
@smk762 LGTM

**Review by CharlVS — APPROVED** [review]

**Review by naezith — APPROVED** [review]
Nothing caught my eye in the changed code.

**Review by endrilickollari — APPROVED** [review]
Looks good on Andorid  👍🏻

**Review by ca333 — APPROVED** [review]

**Comment by ca333** [comment]
changed base to `dev` - propagation path is feature-branch -> dev -> master/main

**Pull request merged**
