### PR TITLE
Release 0.6.3: Update Vote Coins

### PR DESCRIPTION
**Pull request by CharlVS**
All commits tested in #9 

@smk762 Are there any other additions which need to go out with the next release?

[Release notes](https://github.com/KomodoPlatform/atomicdex-mobile/pull/12#issuecomment-1502213280):

> Description:
> 
> This PR aims to merge the changes from the dev branch into master for the release of version 0.6.3. The primary focus of this release is the integration of VOTE2023 and the removal of KIP0001.
> 
> Changelog:
> 
> 1. **Save API binaries as artefacts**: Improved the build process by saving API binaries as artefacts.
> 2. **Delist KIP0001**: Removed KIP0001 as the poll has been completed.
> 3. **Add VOTE2023**: Integrated the VOTE2023 coin into the coins repo.
> 4. **Make VOTE2023 default and wallet-only coin**: Updated VOTE2023 settings to be a wallet-only coin and activated by default for increased visibility.
> 5. **Update README**: Beautify README.
> 6. **Add License**: add MIT License info.

### CODE REVIEW

**Comment by smk762** [comment]
I cant think of anything critical blocking VOTE2023 release.

**Comment by CharlVS** [comment]
Description:

This PR aims to merge the changes from the dev branch into master for the release of version 0.6.3. The primary focus of this release is the integration of VOTE2023 and the removal of KIP0001.

Changelog:

1. **Save API binaries as artifacts**: Improved the build process by saving API binaries as artifacts.
2. **Delist KIP0001**: Removed KIP0001 as the poll has been completed.
3. **Add VOTE2023**: Integrated the VOTE2023 coin into the coins repo.
4. **Make VOTE2023 default and wallet-only coin**: Updated VOTE2023 settings to be a wallet-only coin and activated by default for increased visibility.

**Review by smk762 — DISMISSED** [review]
Looks good here, thanks!

**Review by Canialon — APPROVED** [review]

**Comment by Canialon** [comment]
looks good:) Vote2023 is default and all functionality also worked nicely. No KIP0001 in the app

**Review by smk762 — APPROVED** [review]

**Review by Canialon — DISMISSED** [review]

**Pull request merged**
